/*========== User Section ============*/
// Sign in
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS'
export const SIGNIN_USER_FAIL = 'SIGNIN_USER_FAIL'
// Sign up
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL'
// General
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'

/*========== App Section ============*/
export const ADD_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_TIME_AND_LOC_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_TIME_AND_LOC_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_HUMANS_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_HUMANS_TO_NEWOBSERVATIONS_SUCCESS';
export const ADD_ANIMALS_TO_NEWOBSERVATIONS_SUCCESS = 'ADD_ANIMALS_TO_NEWOBSERVATIONS_SUCCESS';
export const RETRIEVE_OBSERVATIONS_SUCCESS = 'RETRIEVE_OBSERVATIONS_SUCCESS'
export const RETRIEVE_NEW_OBSERVATIONS_SUCCESS = 'RETRIEVE_NEW_OBSERVATIONS_SUCCESS'
export const SET_STATUS = 'SET_STATUS'
export const SYNC_OBSERVATIONS_SUCCESS = 'SYNC_OBSERVATIONS_SUCCESS'
export const UPLOAD_NEW_OBSERVATION_SUCCESS = 'UPLOAD_NEW_OBSERVATION_SUCCESS'
export const UPLOAD_NEW_OBSERVATION_FAIL = 'UPLOAD_NEW_OBSERVATION_FAIL'
export const ADD_TEMP_OBSERVATION_SUCCESS = 'ADD_TEMP_OBSERVATION_SUCCESS'
export const ADD_IMG_TIME_LOCATION_SUCCESS = 'ADD_IMG_TIME_LOCATION_SUCCESS'
export const ADD_ANIMALS_SUCCESS = 'ADD_ANIMALS_SUCCESS'
export const UPLOAD_TEMP_OBSERVATION_SUCCESS = 'UPLOAD_TEMP_OBSERVATION_SUCCESS'
export const UPLOAD_TEMP_OBSERVATION_FAIL = 'UPLOAD_TEMP_OBSERVATION_FAIL'