export default data = [
{id:1,name:"Garbage > Plastic bag"},
{id:2,name:"Garbage > Plastic bottle"},
{id:3,name:"Garbage > Bottle cap"},
{id:4,name:"Garbage > Diaper"},
{id:5,name:"Garbage > Elastic band"},
{id:6,name:"Garbage > Cigarette butt"},
{id:7,name:"Garbage > Balloon"},
{id:8,name:"Garbage > Straw"},
{id:9,name:"Garbage > Chip/food wrapper"},
{id:10,name:"Garbage > Glass bottle"},
{id:11,name:"Garbage > Other"},
{id:12,name:"Garbage > Derelict fishing gear (ghost gear)"},
{id:13,name:"Ship/Vessel/Boat > Shipping vessel"},
{id:14,name:"Ship/Vessel/Boat > Sailboats"},
{id:15,name:"Ship/Vessel/Boat > Cruise ships"},
{id:16,name:"Ship/Vessel/Boat > Yacht"},
{id:17,name:"Ship/Vessel/Boat > Superyacht"},
{id:18,name:"Ship/Vessel/Boat > Daycruiser/Sport boat"},
{id:19,name:"Ship/Vessel/Boat > Overnight cruiser"},
{id:20,name:"Ship/Vessel/Boat > Small fishing"},
{id:21,name:"Ship/Vessel/Boat > Large commercial fishing"},
{id:22,name:"Ship/Vessel/Boat > Kayak"},
{id:23,name:"Ship/Vessel/Boat > Canoe"},
{id:24,name:"Ship/Vessel/Boat > Dive "},
{id:25,name:"Ship/Vessel/Boat > Longtail"},
{id:26,name:"Ship/Vessel/Boat > Small artisanal fishing"},
{id:27,name:"Ship/Vessel/Boat > Jetski"},
{id:28,name:"Ship/Vessel/Boat > Government research vessel"},
{id:29,name:"Ship/Vessel/Boat > Government defence vessel"},
{id:30,name:"Ship/Vessel/Boat > Aircraft carriers"},
{id:31,name:"Ship/Vessel/Boat > Whale watching"},
{id:32,name:"Ship/Vessel/Boat > Zodiac"},
{id:33,name:"Sport > Surfboard"},
{id:34,name:"Sport > SUP (Standup Paddleboard)"},
{id:35,name:"Structure > Oil rig"},
{id:36,name:"Structure > Windmill"},
{id:37,name:"Structure > Fishing Weir"},
{id:38,name:"Structure > Wreck"},
{id:39,name:"Fishing > Lobster buoy"},
{id:40,name:"Fishing > Large net towed behind boat"},
{id:41,name:"Fishing > Beach nets"},
{id:42,name:"Fishing > Shore/dock fishing with rod and hook"},
{id:43,name:"Fishing > Boat fishing with rod and hook"},
{id:44,name:"Fishing > Bomb fishing "},
{id:45,name:"Aquaculture > Offshore aquaculture nets"},
{id:46,name:"Aquaculture > Inshore aquaculture nets"},
{id:47,name:"Sport > Scuba divers"},
{id:48,name:"Sport > Snorkelers"},
{id:49,name:"Pollution > Wastewater discharge pipe"},
{id:50,name:"Pollution > Boat waste dump"},
{id:51,name:"Pollution > Oil spill"},
{id:52,name:"Pollution > Agricultural runoff"},
{id:53,name:"Pollution > Sediment runoff"},
{id:54,name:"Noise > Blasting"}
]